### ISSUE TITLE
Concept hostage traits

### ISSUE THREAD

**Issue by yeslayla** [josephbmanley/LudumDare43#8]
What kind of hostage traits would be cool or interesting to add? Like effects that the hostages have?

**Comment by KidKoda** [comment]
Maybe some hostages are heavy set enough to stun guards for a period of time?

**Comment by LiteralFilth** [comment]
I feel like traits may be a little weird in a gameplay setting if we bind them to a random generation. Even if we add cool traits the fact they are randomly picked it makes knowing the traits kind-of pointless. If we add traits it needs to be in a selectable manner, like a group of hostages sharing a trait that you can choose as a loadout that can be unlocked through the normal unlocking process. I just see traits + randomness could make things a little awkward

**Comment by yeslayla** [comment]
@LiteralFilth Are you thinking this specific issue should be put into the backlog until we improve hostage selection?
